# Generated by Django 4.2.7 on 2024-03-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
